version: '2'
services:
    jmaster-app:
        image: jmaster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jmaster-postgresql:5432/jmaster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jmaster-postgresql:
        extends:
            file: postgresql.yml
            service: jmaster-postgresql
